[project]
name = "tfm-opt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "matplotlib>=3.10.6",
    "scipy>=1.16.2",
    "jax>=0.7.1",
    "pyoptsparse",
    "imageio>=2.37.0",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "scienceplots>=2.1.1",
    "typing-extensions>=4.15.0",
    "cyipopt>=1.6.1",
    "black>=25.1.0",
]

[tool.black]
line-length = 120

[tool.uv.sources]
pyoptsparse = { git = "https://github.com/mdolab/pyoptsparse.git" }
